# Generated by Django 3.2.6 on 2024-10-08 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cronogramasAlumnos', '0002_auto_20241007_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('referencia_pago', models.CharField(max_length=255)),
                ('valor_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cronogramaAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cronogramasAlumnos.cronogramaalumno')),
            ],
        ),
    ]
