# Generated by Django 3.2.6 on 2024-10-08 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='jornada',
        ),
        migrations.AddField(
            model_name='curso',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instituciones.institucion'),
        ),
    ]
