# Generated by Django 3.2.6 on 2024-10-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20241007_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='anio',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
