# Generated by Django 3.2.6 on 2024-10-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('documentoIdentidad', models.IntegerField(primary_key=True, serialize=False)),
                ('curso', models.ManyToManyField(to='cursos.Curso')),
            ],
        ),
    ]
