# Generated by Django 3.2.6 on 2024-10-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='documentoIdentidad',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
