# Generated by Django 3.2.6 on 2024-10-06 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('Matricula', 'Matricula'), ('Pension', 'Pension'), ('Otro Pago', 'Otro Pago')], max_length=9)),
                ('mes', models.CharField(max_length=10)),
                ('alumno', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
            ],
        ),
    ]
